import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner/Banner";
import Nav from "../components/nav/Nav";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix clone!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav username="olusammy" />
      <Banner
        title="Clifford the red dog"
        subTitle="A very cute dog"
        imgUrl="/static/images/clifford-dog.jpeg"
      />
    </div>
  );
}
